### PR TITLE
add additional version of "Today Was A Fairytale"

### PR DESCRIPTION
**Pull request by m-treadway**
Updates mapping to include a second version of "Today Was A Fairytale"

### CODE REVIEW

**Comment by Roshy10** [comment]
Nice spot looks good, thanks!

**Comment by Roshy10** [comment]
ok, the deploy action has finished for the staging environment (https://staging.taylors-version.com/) would you be able to give it a quick test there, then assuming it all goes well (it probably will) just open a pr for develop into master and I'll get it into prod

**Comment by m-treadway** [comment]
Testing went well, but when attempting to open a PR to merge develop into master I'm getting the following error message: `Pull request creation failed. Validation failed: You can't perform that action at this time.`

**Comment by Roshy10** [comment]
ahh ok no worries, I'll just do it :) Thanks for contributing!

**Comment by m-treadway** [comment]
np, happy to help! :)

**Pull request merged**
