### PR TITLE
Full updates for 1989 (checked all tracks with script!)

### PR DESCRIPTION
**Pull request by melvinmcrn**
updates from PR #96 (kudos to @ShamblesSM ) + from what @Roshy10 has pushed to develop from 1989 (I merged them all + check and group incorrect tracks to the correct group!)

+ I also add `th.json` since there are so many Thai Swifties who can better understand this platform! :)

Output from script to check each track:
```text
[replacement]: 'title': Welcome To New York (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Welcome To New York | 'album': 1989, id: spotify:track:10nqz67NQWWa7XPq7ycihi
[original]: 'title': Welcome To New York | 'album': 1989 (Deluxe), id: spotify:track:3nRmDz7qGCvsMS30rGGY0x
[original]: 'title': Welcome To New York | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:3YLA3NgzFRRa7LiHMtFPby
[original]: 'title': Welcome To New York | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:7aMftpNNJiQj1c2rllc8Dk
[original]: 'title': Welcome To New York | 'album': Pride Month, id: spotify:track:1YYOx55cW5JfMe65zEHBdu
[original]: 'title': Welcome To New York | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:3YLA3NgzFRRa7LiHMtFPby

###########################################

[replacement]: 'title': Blank Space (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Blank Space | 'album': 1989, id: spotify:track:2ls70nUDfjzm1lSRDuKxmw
[original]: 'title': Blank Space | 'album': 1989 (Deluxe), id: spotify:track:1u8c2t2Cy7UBoG4ArRcF5g
[original]: 'title': Blank Space | 'album': Gameday Country, id: spotify:track:3LB2qckfpZq7aybaoZKRa2
[original]: 'title': Blank Space | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1kHEuJRasudLhjvnbfc4yS
[original]: 'title': Blank Space | 'album': Big Machine #1's, Volume 4, id: spotify:track:0jjIPthFhpbBNr4my8cePO

###########################################

[replacement]: 'title': Style (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Style | 'album': 1989, id: spotify:track:71PmZqBXH0RUETqxpwlV0w
[original]: 'title': Style | 'album': 1989 (Deluxe), id: spotify:track:0ug5NqcwcFR2xrfTkc7k8e
[original]: 'title': Style | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:4D7kxLhSz7siCOw7KA5rQn
[original]: 'title': Style | 'album': Big Machine #1's, Volume 4, id: spotify:track:60636BsHWxFi7SfYxbP0UV

###########################################

[replacement]: 'title': Out Of The Woods (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Out Of The Woods | 'album': 1989, id: spotify:track:7EpVQjqtKygiwJIASxMWNg
[original]: 'title': Out Of The Woods | 'album': 1989 (Deluxe), id: spotify:track:0qUnBLZ8bJqUNEeQgayL9t
[original]: 'title': Out Of The Woods | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:7CkJgmJ3RFU6jNXNHgRkBw
[original]: 'title': Out Of The Woods | 'album': Pride Month 2021, id: spotify:track:6YHzSWA80uf3LHYMGoDZlM
[original]: 'title': Out Of The Woods | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:0GmfiNHSgkKamYgQEMYOH3
[original]: 'title': Out Of The Woods | 'album': Pride Month, id: spotify:track:2zbVATcYiggJSWeSZkDFgd

###########################################

[replacement]: 'title': All You Had To Do Was Stay (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': All You Had To Do Was Stay | 'album': 1989, id: spotify:track:4NNolUeL5m2ju7kf8pdg6H
[original]: 'title': All You Had To Do Was Stay | 'album': 1989 (Deluxe), id: spotify:track:6aLOekfwbytwWvQftxTEF0
[original]: 'title': All You Had To Do Was Stay | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:50Pu9HKAcPm8TFL2zDrouh

###########################################

[replacement]: 'title': Shake It Off (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Shake It Off | 'album': 1989, id: spotify:track:1kKlhuQE0HXp1IwBRpaH2P
[original]: 'title': Shake It Off | 'album': 1989 (Deluxe), id: spotify:track:0cqRj7pUJDkTCEsJkx8snD
[original]: 'title': Shake It Off | 'album': Pride Month 2023, id: spotify:track:0PEZYlPV0BxoLl9M3pjVnP
[original]: 'title': Shake It Off | 'album': Big Machine's Women Of Country, id: spotify:track:5pJvzBpE1KSMxEgMg5Ft31
[original]: 'title': Shake It Off | 'album': For Your Quarantine, id: spotify:track:6PRELLjOe8RaRIcW0sHskx
[original]: 'title': Shake It Off | 'album': Women Of Big Machine, id: spotify:track:4ZspJzYIxOztSc9hZmcLzH
[original]: 'title': Shake It Off | 'album': Hope: Songs Of Love & Strength, id: spotify:track:2JH2oziHRcxEFUHgfZNm2S
[original]: 'title': Shake It Off | 'album': Country Workout, Volume 2, id: spotify:track:4mEk3TJYIxh1ISDzEpkYoF
[original]: 'title': Shake It Off | 'album': Big Machine #1's, Volume 4, id: spotify:track:5oID3Qj3tTCZEH9eo0snxm
[original]: 'title': Shake It Off | 'album': New Year's Party Country, id: spotify:track:3OtAiLvFzNB8KMnzdyHVnq
[original]: 'title': Shake It Off | 'album': Pride Month 2021, id: spotify:track:7BNBo9g7x0EK46d44HFkKH
[original]: 'title': Shake It Off | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1CiVz2WkmZRwhU3A6J2Gjz
[original]: 'title': Shake It Off | 'album': Pride Month 2022, id: spotify:track:4RPkqiTSRzdo0RPg13bE8n
[original]: 'title': Shake It Off | 'album': Big Machine Dance Party, id: spotify:track:6zpQwkOGOTt6OCnMdNKjHl
[original]: 'title': Shake It Off | 'album': Pride Month, id: spotify:track:21txIeEaimkRCzPOH8L9HG

###########################################

[replacement]: 'title': I Wish You Would (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': I Wish You Would | 'album': 1989, id: spotify:track:5RVJ6VKfwtosA5Q1qeHdjF
[original]: 'title': I Wish You Would | 'album': 1989 (Deluxe), id: spotify:track:5gRYrtvyVyaCRvLt56OfuV
[original]: 'title': I Wish You Would | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:3JPOspEefgmGT5Hyy11oQJ
[original]: 'title': I Wish You Would | 'album': Country Workout, Volume 1, id: spotify:track:0t0MOVBcdiOXS8FblHewBx

###########################################

[replacement]: 'title': Bad Blood (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Bad Blood | 'album': 1989, id: spotify:track:0TvQLMecTE8utzoNmvXRbK
[original]: 'title': Bad Blood | 'album': 1989 (Deluxe), id: spotify:track:2NlmmAjGYrrjAp0MED5rGx
[original]: 'title': Bad Blood | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:4SHyS2ThjrS1iBGruKweCz
[original]: 'title': Bad Blood | 'album': Bad Blood, id: spotify:track:6xsEAm6w9oMQYYg3jkEkMT
[original]: 'title': Bad Blood | 'album': Be My Anti-Valentine 2022, id: spotify:track:5QmXcfqaz8TobfNbkoDHvP

###########################################

[replacement]: 'title': Wildest Dreams (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Wildest Dreams (Taylor's Version) | 'album': Wildest Dreams (Taylor's Version), id: spotify:track:1Ov37jtRQ2YNAe8HzfczkL
[original]: 'title': Wildest Dreams | 'album': 1989, id: spotify:track:3fVnlF4pGqWI9flVENcT28
[original]: 'title': Wildest Dreams | 'album': 1989 (Deluxe), id: spotify:track:4A4A6dwl5DqdqrZaEtKGPR
[original]: 'title': Wildest Dreams | 'album': 1989, id: spotify:track:59HjlYCeBsxdI0fcm3zglw
[original]: 'title': Wildest Dreams | 'album': 1989 (Deluxe Edition), id: spotify:track:106R7Z57WYzBAfrXImV30y
[original]: 'title': Wildest Dreams | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:22C0JIVhFaczZ4t9heqREN
[original]: 'title': Wildest Dreams | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:3ScVaMDQwaD8iumBYzcDvr

###########################################

[replacement]: 'title': How You Get The Girl (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': How You Get The Girl | 'album': 1989, id: spotify:track:5Z9ocF6ng0m2haHnKtHwTp
[original]: 'title': How You Get The Girl | 'album': 1989 (Deluxe), id: spotify:track:0fM9dEhUFV4MHDuJgrcfOv
[original]: 'title': How You Get The Girl | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1l6KjnsqP2atawKgBV49u3
[original]: 'title': How You Get The Girl | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:3aSYZ4upQ6OSNos26YeVWL

###########################################

[replacement]: 'title': This Love (Taylor’s Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': This Love (Taylor’s Version) | 'album': This Love (Taylor’s Version), id: spotify:track:4d1CG5ei1E2vGbvmgf5KKv
[original]: 'title': This Love | 'album': 1989, id: spotify:track:7lTxQZVXlvIX7Z3szSy8Sh
[original]: 'title': This Love | 'album': 1989 (Deluxe), id: spotify:track:4L560fic5PaTuCFm6CviKa
[original]: 'title': This Love | 'album': 1989, id: spotify:track:3oKMl2tJv4fdidkXUYMI5x
[original]: 'title': This Love | 'album': 1989 (Deluxe Edition), id: spotify:track:1kTPQnabROVkW9bUXdCGrB
[original]: 'title': This Love | 'album': 1989 (Deluxe Edition), id: spotify:track:28VqgFAhYCU7FdAm7dvEjp
[original]: 'title': This Love | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:64KRxmbqypPBlya4nxFmDn
[original]: 'title': This Love | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:5yCRSEPJXzjzl3Gov0YduA

###########################################

[replacement]: 'title': I Know Places (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': I Know Places | 'album': 1989, id: spotify:track:6Ck9WerfsyvC4v4AylUoDp
[original]: 'title': I Know Places | 'album': 1989 (Deluxe), id: spotify:track:6EwNJz8CuVsrsLvXprJ20Q
[original]: 'title': I Know Places | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1fDfzSgIEFWDuX383vRiAv
[original]: 'title': I Know Places | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:3qGLcmO0XnnrcpAQGZwTvA

###########################################

[replacement]: 'title': Clean (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Clean | 'album': 1989, id: spotify:track:2k43eySbfpDVx0PrO99UI8
[original]: 'title': Clean | 'album': 1989 (Deluxe), id: spotify:track:1NmVZsG18CzCAtw7rnV3yA
[original]: 'title': Clean | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1s4CiRufJUyeyQT6HRmu7S

###########################################

[replacement]: 'title': Wonderland (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': Wonderland | 'album': 1989 (Deluxe), id: spotify:track:6RvRzl1YJTDnUvdOtV21IK
[original]: 'title': Wonderland | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:0eTCaVOYLpJlSkbEi2jay4

###########################################

[replacement]: 'title': You Are In Love (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': You Are In Love | 'album': 1989 (Deluxe), id: spotify:track:2KrOAg6FftbjgSKdd2a4rS
[original]: 'title': You Are In Love | 'album': Great Big Love Songs, id: spotify:track:5CMw15fx1o2OW2jzaYy36L

###########################################

[replacement]: 'title': New Romantics (Taylor's Version) | 'album': 1989 (Taylor's Version)
---------------------------------------------
[original]: 'title': New Romantics | 'album': 1989 (Deluxe), id: spotify:track:0qAIiGFKLdV1xpNlEhjpq8

###########################################

```

### CODE REVIEW

**Comment by ShamblesSM** [comment]
Looks good! Could you perhaps share a gist/repo to the Spotify search script that you used? It'd be a great help to those who wish to contribute to the project too, as it seems like I've missed a handful of copies for Shake It Off under multiple albums.

**Comment by Roshy10** [comment]
Please could you pull the translations into a separate PR and I'll be happy to merge them

**Comment by ShamblesSM** [comment]
Looks like there's now a Deluxe version of 1989 TV, which includes 1 new track (Bad Blood ft. Kendrick Lamar TV):
https://open.spotify.com/track/6qAcApH8obo8eqatCKUHd9?si=4f39689f3e2e454d

**Comment by Roshy10** [comment]
I also ask that you update this pull request so it's not shuffling the order of the tracks around so much, it makes it difficult to review what's actually changed.

**Comment by ShamblesSM** [comment]
The variable name (`_1989` instead of `album_1989`) was from my fork, as @melvinmcrn used my fork as a base.

**Comment by melvinmcrn** [comment]
Yeah. This PR is based on @ShamblesSM 's PR. But I'll update them to be as much similar to @Roshy10 's develop branch as possible.

ps. just separate the TH language to PR #104 
ps2. I think I'll update the new version to be deluxe?

**Comment by melvinmcrn** [comment]
> Looks good! Could you perhaps share a gist/repo to the Spotify search script that you used? It'd be a great help to those who wish to contribute to the project too, as it seems like I've missed a handful of copies for Shake It Off under multiple albums.

@ShamblesSM My script is just for checking the current data to see each track name (cause in the data, we use the spotify track ID which is hard to check if it's correct.)

I quick written it in python + hardcoded the bearer token (spotify's API need to auth first) so maybe I'll need to do some more improvement first.

**Comment by melvinmcrn** [comment]
Updated result from script

```
[replacement]: 'title': Welcome To New York (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Welcome To New York | 'album': 1989, id: spotify:track:10nqz67NQWWa7XPq7ycihi
[original]: 'title': Welcome To New York | 'album': 1989 (Deluxe), id: spotify:track:3nRmDz7qGCvsMS30rGGY0x
[original]: 'title': Welcome To New York | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:3YLA3NgzFRRa7LiHMtFPby
[original]: 'title': Welcome To New York | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:7aMftpNNJiQj1c2rllc8Dk
[original]: 'title': Welcome To New York | 'album': Pride Month, id: spotify:track:1YYOx55cW5JfMe65zEHBdu
[original]: 'title': Welcome To New York | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:3YLA3NgzFRRa7LiHMtFPby
[original]: 'title': Welcome To New York (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:1hR8BSuEqPCCZfv93zzzz9

###########################################

[replacement]: 'title': Blank Space (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Blank Space | 'album': 1989, id: spotify:track:2ls70nUDfjzm1lSRDuKxmw
[original]: 'title': Blank Space | 'album': 1989 (Deluxe), id: spotify:track:1u8c2t2Cy7UBoG4ArRcF5g
[original]: 'title': Blank Space | 'album': Gameday Country, id: spotify:track:3LB2qckfpZq7aybaoZKRa2
[original]: 'title': Blank Space | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1kHEuJRasudLhjvnbfc4yS
[original]: 'title': Blank Space | 'album': Big Machine #1's, Volume 4, id: spotify:track:0jjIPthFhpbBNr4my8cePO
[original]: 'title': Blank Space (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:45wMBGri1PORPjM9PwFfrS

###########################################

[replacement]: 'title': Style (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Style | 'album': 1989, id: spotify:track:71PmZqBXH0RUETqxpwlV0w
[original]: 'title': Style | 'album': 1989 (Deluxe), id: spotify:track:0ug5NqcwcFR2xrfTkc7k8e
[original]: 'title': Style | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:4D7kxLhSz7siCOw7KA5rQn
[original]: 'title': Style | 'album': Big Machine #1's, Volume 4, id: spotify:track:60636BsHWxFi7SfYxbP0UV
[original]: 'title': Style (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:1hjRhYpWyqDpPahmSlUTlc

###########################################

[replacement]: 'title': Out Of The Woods (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Out Of The Woods | 'album': 1989, id: spotify:track:7EpVQjqtKygiwJIASxMWNg
[original]: 'title': Out Of The Woods | 'album': 1989 (Deluxe), id: spotify:track:0qUnBLZ8bJqUNEeQgayL9t
[original]: 'title': Out Of The Woods | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:7CkJgmJ3RFU6jNXNHgRkBw
[original]: 'title': Out Of The Woods | 'album': Pride Month 2021, id: spotify:track:6YHzSWA80uf3LHYMGoDZlM
[original]: 'title': Out Of The Woods | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:0GmfiNHSgkKamYgQEMYOH3
[original]: 'title': Out Of The Woods | 'album': Pride Month, id: spotify:track:2zbVATcYiggJSWeSZkDFgd
[original]: 'title': Out Of The Woods (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:045ZeOHPIzhxxsm8bq5kyE

###########################################

[replacement]: 'title': All You Had To Do Was Stay (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': All You Had To Do Was Stay | 'album': 1989, id: spotify:track:4NNolUeL5m2ju7kf8pdg6H
[original]: 'title': All You Had To Do Was Stay | 'album': 1989 (Deluxe), id: spotify:track:6aLOekfwbytwWvQftxTEF0
[original]: 'title': All You Had To Do Was Stay | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:50Pu9HKAcPm8TFL2zDrouh
[original]: 'title': All You Had To Do Was Stay (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:6GXgd1BPD9bUpqw5AntGV5

###########################################

[replacement]: 'title': Shake It Off (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Shake It Off | 'album': 1989, id: spotify:track:1kKlhuQE0HXp1IwBRpaH2P
[original]: 'title': Shake It Off | 'album': 1989 (Deluxe), id: spotify:track:0cqRj7pUJDkTCEsJkx8snD
[original]: 'title': Shake It Off | 'album': Pride Month 2023, id: spotify:track:0PEZYlPV0BxoLl9M3pjVnP
[original]: 'title': Shake It Off | 'album': Big Machine's Women Of Country, id: spotify:track:5pJvzBpE1KSMxEgMg5Ft31
[original]: 'title': Shake It Off | 'album': For Your Quarantine, id: spotify:track:6PRELLjOe8RaRIcW0sHskx
[original]: 'title': Shake It Off | 'album': Women Of Big Machine, id: spotify:track:4ZspJzYIxOztSc9hZmcLzH
[original]: 'title': Shake It Off | 'album': Hope: Songs Of Love & Strength, id: spotify:track:2JH2oziHRcxEFUHgfZNm2S
[original]: 'title': Shake It Off | 'album': Country Workout, Volume 2, id: spotify:track:4mEk3TJYIxh1ISDzEpkYoF
[original]: 'title': Shake It Off | 'album': Big Machine #1's, Volume 4, id: spotify:track:5oID3Qj3tTCZEH9eo0snxm
[original]: 'title': Shake It Off | 'album': New Year's Party Country, id: spotify:track:3OtAiLvFzNB8KMnzdyHVnq
[original]: 'title': Shake It Off | 'album': Pride Month 2021, id: spotify:track:7BNBo9g7x0EK46d44HFkKH
[original]: 'title': Shake It Off | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1CiVz2WkmZRwhU3A6J2Gjz
[original]: 'title': Shake It Off | 'album': Pride Month 2022, id: spotify:track:4RPkqiTSRzdo0RPg13bE8n
[original]: 'title': Shake It Off | 'album': Big Machine Dance Party, id: spotify:track:6zpQwkOGOTt6OCnMdNKjHl
[original]: 'title': Shake It Off | 'album': Pride Month, id: spotify:track:21txIeEaimkRCzPOH8L9HG
[original]: 'title': Shake It Off (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:3pv7Q5v2dpdefwdWIvE7yH

###########################################

[replacement]: 'title': I Wish You Would (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': I Wish You Would | 'album': 1989, id: spotify:track:5RVJ6VKfwtosA5Q1qeHdjF
[original]: 'title': I Wish You Would | 'album': 1989 (Deluxe), id: spotify:track:5gRYrtvyVyaCRvLt56OfuV
[original]: 'title': I Wish You Would | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:3JPOspEefgmGT5Hyy11oQJ
[original]: 'title': I Wish You Would | 'album': Country Workout, Volume 1, id: spotify:track:0t0MOVBcdiOXS8FblHewBx
[original]: 'title': I Wish You Would (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:43y1WpBdnEy5TR9aZoSQL9

###########################################

[replacement]: 'title': Bad Blood (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Bad Blood | 'album': 1989, id: spotify:track:0TvQLMecTE8utzoNmvXRbK
[original]: 'title': Bad Blood | 'album': 1989 (Deluxe), id: spotify:track:2NlmmAjGYrrjAp0MED5rGx
[original]: 'title': Bad Blood | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:4SHyS2ThjrS1iBGruKweCz
[original]: 'title': Bad Blood | 'album': Bad Blood, id: spotify:track:6xsEAm6w9oMQYYg3jkEkMT
[original]: 'title': Bad Blood | 'album': Be My Anti-Valentine 2022, id: spotify:track:5QmXcfqaz8TobfNbkoDHvP
[original]: 'title': Bad Blood (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:64FzgoLZ3oXu2SriZblHic

###########################################

[replacement]: 'title': Wildest Dreams (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Wildest Dreams (Taylor's Version) | 'album': Wildest Dreams (Taylor's Version), id: spotify:track:1Ov37jtRQ2YNAe8HzfczkL
[original]: 'title': Wildest Dreams | 'album': 1989, id: spotify:track:3fVnlF4pGqWI9flVENcT28
[original]: 'title': Wildest Dreams | 'album': 1989 (Deluxe), id: spotify:track:4A4A6dwl5DqdqrZaEtKGPR
[original]: 'title': Wildest Dreams | 'album': 1989, id: spotify:track:59HjlYCeBsxdI0fcm3zglw
[original]: 'title': Wildest Dreams | 'album': 1989 (Deluxe Edition), id: spotify:track:106R7Z57WYzBAfrXImV30y
[original]: 'title': Wildest Dreams | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:22C0JIVhFaczZ4t9heqREN
[original]: 'title': Wildest Dreams | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:3ScVaMDQwaD8iumBYzcDvr
[original]: 'title': Wildest Dreams (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:1K39ty6o1sHwwlZwO6a7wK

###########################################

[replacement]: 'title': How You Get The Girl (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': How You Get The Girl | 'album': 1989, id: spotify:track:5Z9ocF6ng0m2haHnKtHwTp
[original]: 'title': How You Get The Girl | 'album': 1989 (Deluxe), id: spotify:track:0fM9dEhUFV4MHDuJgrcfOv
[original]: 'title': How You Get The Girl | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1l6KjnsqP2atawKgBV49u3
[original]: 'title': How You Get The Girl | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:3aSYZ4upQ6OSNos26YeVWL
[original]: 'title': How You Get The Girl (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:75W3SngKzTuoQ94uLf3y82

###########################################

[replacement]: 'title': This Love (Taylor’s Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': This Love (Taylor’s Version) | 'album': This Love (Taylor’s Version), id: spotify:track:4d1CG5ei1E2vGbvmgf5KKv
[original]: 'title': This Love | 'album': 1989, id: spotify:track:7lTxQZVXlvIX7Z3szSy8Sh
[original]: 'title': This Love | 'album': 1989 (Deluxe), id: spotify:track:4L560fic5PaTuCFm6CviKa
[original]: 'title': This Love | 'album': 1989, id: spotify:track:3oKMl2tJv4fdidkXUYMI5x
[original]: 'title': This Love | 'album': 1989 (Deluxe Edition), id: spotify:track:1kTPQnabROVkW9bUXdCGrB
[original]: 'title': This Love | 'album': 1989 (Deluxe Edition), id: spotify:track:28VqgFAhYCU7FdAm7dvEjp
[original]: 'title': This Love | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:64KRxmbqypPBlya4nxFmDn
[original]: 'title': This Love | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:5yCRSEPJXzjzl3Gov0YduA
[original]: 'title': This Love (Taylor’s Version) | 'album': 1989 (Taylor's Version), id: spotify:track:5QVVjX0ZItqlVpEuVCM9Yg

###########################################

[replacement]: 'title': I Know Places (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': I Know Places | 'album': 1989, id: spotify:track:6Ck9WerfsyvC4v4AylUoDp
[original]: 'title': I Know Places | 'album': 1989 (Deluxe), id: spotify:track:6EwNJz8CuVsrsLvXprJ20Q
[original]: 'title': I Know Places | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1fDfzSgIEFWDuX383vRiAv
[original]: 'title': I Know Places | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:3qGLcmO0XnnrcpAQGZwTvA
[original]: 'title': I Know Places (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:2f0GI2ZLUtbGqFx8t2Gk6A

###########################################

[replacement]: 'title': Clean (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Clean | 'album': 1989, id: spotify:track:2k43eySbfpDVx0PrO99UI8
[original]: 'title': Clean | 'album': 1989 (Deluxe), id: spotify:track:1NmVZsG18CzCAtw7rnV3yA
[original]: 'title': Clean | 'album': 1989 (Big Machine Radio Release Special), id: spotify:track:1s4CiRufJUyeyQT6HRmu7S
[original]: 'title': Clean (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:2ByBBvpR9b7IynvRmnG7kG

###########################################

[replacement]: 'title': Wonderland (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Wonderland | 'album': 1989 (Deluxe), id: spotify:track:6RvRzl1YJTDnUvdOtV21IK
[original]: 'title': Wonderland | 'album': reputation Stadium Tour Surprise Song Playlist, id: spotify:track:0eTCaVOYLpJlSkbEi2jay4
[original]: 'title': Wonderland (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:2ve0kuaWUCt4Zx8x4bf1MR

###########################################

[replacement]: 'title': You Are In Love (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': You Are In Love | 'album': 1989 (Deluxe), id: spotify:track:2KrOAg6FftbjgSKdd2a4rS
[original]: 'title': You Are In Love | 'album': Great Big Love Songs, id: spotify:track:5CMw15fx1o2OW2jzaYy36L
[original]: 'title': You Are In Love (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:4UwqOWDpdeIDVQDuKT6iza

###########################################

[replacement]: 'title': New Romantics (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': New Romantics | 'album': 1989 (Deluxe), id: spotify:track:0qAIiGFKLdV1xpNlEhjpq8
[original]: 'title': New Romantics (Taylor's Version) | 'album': 1989 (Taylor's Version), id: spotify:track:2vPMoMDXxu9uX1igWZmXSG

###########################################

[replacement]: 'title': Bad Blood (feat. Kendrick Lamar) (Taylor's Version) | 'album': 1989 (Taylor's Version) [Deluxe]
---------------------------------------------
[original]: 'title': Bad Blood | 'album': Bad Blood, id: spotify:track:6xsEAm6w9oMQYYg3jkEkMT

###########################################
```

**Comment by melvinmcrn** [comment]
@Roshy10 I just pushed updates. It's hard to make it similar to your develop branch since I checked out my branch from @ShamblesSM 's PR. But I have written a script to fetch data of each track ID and printout the track name + album (the result is in the above comment) so feel free to test them (or trust my script? lol)

ps. seem like your latest commit has some error? (https://github.com/Roshy10/taylors-version/commit/e95c41eed5c9f5b5cddfdb670f498b8aff3a6e43)

**Comment by Roshy10** [comment]
Hi, I realised it's not the best idea to use the track URI for matching, and am swapping over to using the track name (pr#105), as such we no longer need these changes. but thank you so much for your help regardless :)

**Pull request closed without merging**
